use_frameworks!
pod 'SkyFloatingLabelTextField', '~> 1.0'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
pod 'Alamofire', '~> 3.4'
pod 'DynamicColor', '~> 2.4.0'
pod 'TOCropViewController'
