# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 23:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoChallengeCore', '0004_challenge_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='challenge',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='PhotoChallengeCore.Challenge'),
        ),
    ]
